name: CI/CD

on:
  push:
    branches: [ creation ]
  pull_request:
    branches: [ creation ]

jobs:
  build:
    name: build using chomp
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Chomp
        uses: guybedford/chomp-action@v1
      - run: chomp deno2.importmap
      # - name: Setup Chomp
      #   uses: guybedford/chomp-action@v1
      # - name: Build with Chomp
      #   run: chomp deno.importmap

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      # - name: Setup Chomp
      #   uses: guybedford/chomp-action@v1
      # - run: chomp deno2.importmap
      # - name: Setup Chomp
      #   uses: guybedford/chomp-action@v1
      - name: Build with Chomp
        run: cat deno2.importmap
      - name: Deploy to Deno Deploy
        uses: guybedford/chomp-action@v1
        uses: denoland/deployctl@v1
        with:
          project: github-actions-deno-chomp # the name of the project on Deno Deploy
          import-map: deno2.importmap
          entrypoint: server.jsx # the entrypoint to deploy