name: CI/CD

on:
  push:
    branches: [ creation ]
  pull_request:
    branches: [ creation ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: github-actions-deno-chomp # the name of the project on Deno Deploy
          entrypoint: server.jsx # the entrypoint to deploy